const textos ={
    inicio:{
            presidente:[
                "Presidente de VenOil Energía con 23 años en el gerenciamiento de proyectos de gas y petróleo en diferentes campos de Argentina.",
                "Ocupó diferentes posiciones técnicas, gerenciales y directivas en empresas como Repsol e YPF.",
                "Su última función directiva estuvo focalizada en los activos del sur de la provincia de Mendoza. Obtuvo diferentes menciones de la alta dirección de ambas empresas, reconociendo sus excelentes resultados.",
                "Gustavo es Ingeniero Electrónico y completó su formación académica capacitándose en programas de Dirección Ejecutiva (IAE) y de Alta Dirección (UCA). Posee amplia experiencia en producción, tratamiento y transporte de gas & petróleo, gerenciamiento de proyectos, negociación con socios, sindicatos y entes gubernamentales.",
                "Es Co-fundador de VenOil Energia. Todo esto hace de Gustavo un especialista de excelencia en la gestión de proyectos de Oil & Gas."],
            valores:["Liderazgo en todas las fases del proyecto","Transparencia en el desempeño","Pasion en cada tarea y nuevo desafío","Respeto por las comunidades y el medio ambiente","Excelencia en todos los niveles de la organización","Integridad como base de todas nuestras decisiones"],
            campos:{
                manzano:"El Manzano Oeste, ubicado en el departamento de Malargüe, es uno de los activos más importantes de Venoil Energía en Mendoza. Fue uno de los primeros yacimientos operados por Venoil, y desde aquí se desarrolló el modelo de negocio que la empresa implementa actualmente. Reconocido por la calidad de su petróleo y su ubicación en una región con rica tradición petrolera, este yacimiento contribuye significativamente al desarrollo económico del sur mendocino. Venoil implementa métodos avanzados de explotación y mantiene un compromiso firme con las comunidades locales, asegurando que la operación en El Manzano Oeste sea un ejemplo de gestión responsable y sostenible, mientras impulsa el crecimiento de Malargüe como un polo petrolero destacado.",
                piedrascoloradas:"El yacimiento Piedras Coloradas, ubicado en la provincia de Mendoza, es una de las operaciones destacadas de Venoil Energía en la región. Recientemente adquirido por la empresa, este yacimiento es reconocido por su producción de petróleo convencional y es un motor económico clave para las comunidades cercanas. Con la implementación de técnicas modernas de extracción y una gestión alineada con las normas ISO 9001, 14001 y 45001, Venoil asegura que las operaciones de Piedras Coloradas sean sostenibles y generen empleo directo e indirecto, fortaleciendo la economía de Mendoza.",
                cacheuta:"Situado en una zona estratégica de Mendoza, el yacimiento Cacheuta, recientemente adquirido por Venoil Energía, es un hito histórico para la industria hidrocarburífera de la región y del país. Este yacimiento fue uno de los primeros en ser explotados a gran escala en Argentina, marcando el inicio de una era de desarrollo energético en el territorio nacional. Su legado trasciende generaciones, y hoy, gracias a la incorporación de tecnologías modernas, sigue siendo una fuente clave de energía y empleo, consolidando su papel como un referente en la historia petrolera de Mendoza y del país.",
                chimenaike:"Chimen Aike, gestionado por Venoil Energía, se encuentra cerca de Río Gallegos y representa un importante activo para la empresa y la provincia. Este yacimiento cuenta con gran potencial en la producción de gas natural y está siendo evaluado para el desarrollo de recursos no convencionales. La operación de Chimen Aike no solo contribuye al crecimiento económico local, sino que también posiciona a Santa Cruz como un referente energético clave para el futuro.",
                canadonsalto:"Operado por Venoil Energía, Cañadón Salto es un yacimiento ubicado en una de las áreas más remotas del sur de Santa Cruz. Se caracteriza por la extracción de petróleo liviano y gas natural, utilizando tecnologías de recuperación secundaria para optimizar su producción. Este yacimiento es fundamental para la provincia, ya que genera recursos económicos, empleo y estabilidad energética, consolidando el compromiso de Venoil con el desarrollo sostenible de la región.",
                maggie:"En el corazón del corredor petrolero central de Santa Cruz, Estancia La Maggie destaca como un yacimiento estratégico de Venoil Energía. Con una producción mixta de petróleo de alta calidad y gas natural, este yacimiento es una fuente importante de recursos para la provincia. A pesar de los desafíos logísticos y climáticos de la región, Venoil ha implementado soluciones efectivas que permiten maximizar el potencial de este activo, generando empleo y contribuyendo al desarrollo económico de las comunidades cercanas.",
                condor:"Ubicado cerca de Río Gallegos, el yacimiento El Cóndor, operado por Venoil Energía, es una pieza clave en la Cuenca Austral. Este yacimiento produce principalmente gas natural, complementado con reservas de petróleo. Su importancia radica en su capacidad para abastecer de energía a la región, conectando su producción con el Gasoducto San Martín. Gracias a la infraestructura de plantas de tratamiento y al uso de tecnologías modernas, El Cóndor no solo genera empleo y desarrollo económico, sino que también asegura un suministro confiable de energía para Santa Cruz y más allá."
            }
    },
    gestionintegrada:{
        principios:["ISO 9001 - Gestión de la Calidad: Esta norma asegura que nuestros procesos estén diseñados para cumplir consistentemente con las expectativas de nuestros clientes,mejorando la eficiencia y fomentando la mejora continua.","ISO 14001 - Gestión Ambiental: Comprometidos con elcuidado del medio ambiente, implementamos esta norma para gestionar de manera responsable los impactos ambientales de nuestras actividades, promoviendo prácticas sostenibles y respetuosas con el entorno.","ISO 45001 - Gestión de la Seguridad y Salud en el Trabajo:Garantizamos la seguridad y el bienestar de nuestros empleados y colaboradores a través de sistemas que identifican, controlan y reducen los riesgos en el entorno laboral","Vigilamos cada detalle para garantizar la seguridad en todas nuestras operaciones."],
        gestion:["Establecemos estándares que protegen a nuestro equipo, las comunidades y el medio ambiente.","Nos comprometemos a prevenir riesgos mediante una gestión proactiva y responsable.","Optimizamos nuestros procesos para garantizar operaciones seguras y eficientes.","Innovamos constantemente en tecnologías que priorizan la seguridad en campo.","Lideramos con el ejemplo, promoviendo una cultura de seguridad en cada proyecto."]
    }
}

export default textos;