import type { Metadata } from "next";
import "./globals.css";
import Nav from "./components/Nav";
import Footer from "./components/Footer";
import { pop } from "./fonts/Fonts";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`antialiased overflow-x-hidden`} style={pop.style}>
        <Nav />
        {children}
        <Footer />
        <div className="bg-blue-950 text-white w-screen h-12 border-t-2 border-white  text-xs flex items-center justify-center">
          © 2024. Todos los derechos reservados por Venoil S.A
        </div>
      </body>
    </html>
  );
}
